server:
  port: 9902

spring:
  application:
    name: micro-user
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.alibaba.druid.proxy.DruidDriver
#    url: jdbc:mysql://localhost:3306/boot?autoReconnect=true&useUnicode=true
#    username: root
#    password: root
    primary:
      url: jdbc:mysql://localhost:3306/micro-service?autoReconnect=true&useUnicode=true
      username: root
      password: root
    secondary:
      url: jdbc:mysql://localhost:3306/micro-service?autoReconnect=true&useUnicode=true
      username: root
      password: root
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


